language: python
python:
    - "3.4"
    - "2.7"
# install dependencies
install: 
    - "make bootstrap-dev"
    - "pip install coveralls"
# do tests
script: 
    - "make test"
# push data to coveralls
after_success: coveralls
